// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDemoApp.WebApi.Data;

#nullable disable

namespace MyDemoApp.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250726121711_Initial_Migration")]
    partial class Initial_Migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MyDemoApp.WebApi.Models.AiModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MaxTokens")
                        .HasColumnType("int");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("ModelId")
                        .IsUnique();

                    b.ToTable("AiModels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 7, 26, 12, 17, 10, 834, DateTimeKind.Utc).AddTicks(4687),
                            Description = "Best for complex tasks with faster response times",
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDefault = true,
                            MaxTokens = 8192,
                            ModelId = "gemini-1.5-flash",
                            Name = "Gemini 1.5 Flash",
                            Provider = "Google",
                            Temperature = 0.7m,
                            UpdatedAt = new DateTime(2025, 7, 26, 12, 17, 10, 834, DateTimeKind.Utc).AddTicks(4754),
                            Version = "1.5"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 7, 26, 12, 17, 10, 834, DateTimeKind.Utc).AddTicks(4818),
                            Description = "Latest model, optimized for chat and simple tasks",
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDefault = false,
                            MaxTokens = 8192,
                            ModelId = "gemini-2.0-flash-001",
                            Name = "Gemini 2.0 Flash",
                            Provider = "Google",
                            Temperature = 0.7m,
                            UpdatedAt = new DateTime(2025, 7, 26, 12, 17, 10, 834, DateTimeKind.Utc).AddTicks(4818),
                            Version = "2.0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
